### ISSUE TITLE
GTM Timetracking lost after interactive rebase

### ISSUE THREAD

**Issue by Korne127** [DEVELOPEST/gtm-core#62]
I use GTM (/this fork of GTM) to track my time, combined with the IntelliJ GTM Enhanced plugin.

The tracking worked fine. However, when I did an interactive rebase (to change a commit message) `git rebase -i <hash>`, the time tracking has been completely lost.
Using "gtm report" just shows the name of the last commit without any time.

Is there any possibility to regain the previously tracked data? And how can I prevent this from happening in the future?

**Comment by kilpkonn** [comment]
What gtm-core version are you using?  
For latest version, there should be `gtm rewrite` command, that is run from `post-rewrite` git hook and it will change notes to keep pointing to commit.

If you know your rebased commit sha (I think it needs to be full length), then you can do `gtm rewrite` and paste
`old_sha new_sha` into stdin (Pretty much mimicking the hook) to recover the lost data.

If your gtm-core version is older, please update it to newest and run `gtm init` again to add correct hooks that will rewrite notes automatically.
If the issue still persists, please let me know and I'll try to fix it.

**Comment by Korne127** [comment]
Thank you for the quick answer, I appreciate it.
I am using version 1.0.2 and the newest IntelliJ plugin as well (at least I think so), so that should not be a problem.
I hesitated thought because of one question.
Besides the hours in the lost commits, I had some time (around 16 minutes) in uncommitted action. That disappeared after the rebase as well. When I run this command now (gtm rewrite), will that
A: Delete the current uncommitted time again
B: Not change the uncommitted time
C: Add the old removed uncommitted time to the current time
I suppose it's B but I'm afraid it will remove it again (A) so I better ask.
And maybe the fact that it removed that uncommitted time as well when rebasing could be considered a bug as well?

Also, how I understood it, to use gtm rewrite, I need the old sha. I guess I'll try to find it via the garbage collection (I haven't cleared it), but it isn't possible to recreate without that, right?.
You said in the newest gtm version it is run automatically by a git hook but there is no release after 1.0.2 so I'm running the newest version (and I have run it when I did that commit), but it didn't do that for me?

**Comment by kilpkonn** [comment]
Thanks for the info. Rewrite should not change uncommitted time at all, but there can be a bug...   
And yes you need old hash, which should be fed into `gtm rewrite` in post rewrite hook automatically.
Please check if you have post rewrite hook calling `gtm rewrite` and let me know.  
Anyways, I believe it is a bug as I've sometimes also encountered it. 
I will look into it in the next week, when I have more time to see why the hooks is sometimes not ran etc.

**Comment by Korne127** [comment]
Thank you for the good help and quick answer!
I checked the original hashes via reflog and did this.
For the commit I rebased / which's message I actually changed I could get that data back (which was the important part!) so thank you so much for that help! :D
For the initial commit (the one before) it didn't work though I got the error message:
> 2021/05/19 01:27:51 object 'b3[…]d3' has no note

In my case, that's not so bad as those were only a few minutes on the .gitignore and pom.xml, but in general it's I guess still something to look into.

Edit: I realised that when I did `gtm report <Hash>` with the new hash of the initial commit, it still saved that data. So I guess the rewrite happened automatically for that commit? Anyways, it was just me not realising that, but I was able to recover all data :D
So, thank you so much for your help :)

**Comment by kilpkonn** [comment]
Ok that's good to hear!

On the other hand it show there has to be a some kind of bug as both of the notes should have been rewritten in a similar way.

Will investigate it next week!

**Comment by kilpkonn** [comment]
Can you try appropriate build from here?: https://github.com/DEVELOPEST/gtm-core/actions/runs/888331927  
  
Make sure to do `gtm uninit`, then upgrade and then `gtm init` or remove `post-rewrite` hook manually as otherwise there might be some issue with duplicating time.  
  
This build worked fine for me with most basic interactive rebase activities and with amend so if it also work for you I'd merge the changes and do new release

**Comment by kilpkonn** [comment]
Closing this issue, as it is hopefully fixed
