### ISSUE TITLE
git notes pushed to remote repo

### ISSUE THREAD

**Issue by bestlinuxgamers** [DEVELOPEST/gtm-core#63]
I use GTM core V1.0.2. with the with the IntelliJ GTM Enhanced plugin.

The gtm git-notes are pushed to the remote-repo for me. This is not optimal especially for collaborative projects. Is there a way to disable this and remove existing ones from the remote?

![grafik](https://user-images.githubusercontent.com/52172848/118528698-edc88c80-b742-11eb-8795-063c616e7b08.png)

**Comment by kilpkonn** [comment]
If you initialize the tracking with `gtm init --local`, then there should be no notes pushed to remote. If you don't have much data recorded, I recommend uninitializing tracking, cleaning notes (also remote) and initializing tracking again.  
If there is data you wish to keep, skip the clean step locally and only delete data from remote. (Make sure you uninit tracking first, cuz otherwise pull might delete local notes)

**Comment by bestlinuxgamers** [comment]
Thanks for the quick reply!
How can I clean the notes?
Also, if I want to keep the data, how can I delete the data only from the remote? I imagine then the uploaded data on remote being differently to the data on my own git repository, at least for the commits I made before this change.
Or will the reinitialising with `--local` change the gtm data from the previous commits in a way that it won't get pushed again?

**Comment by kilpkonn** [comment]
To keep the data do following:
1) Make a full copy of your project (also `.git` folder) <- Just for backup
2) Inside original project type `gtm uninit`
3) To be 100% sure, cd into `.git/hooks` directory inside your project and delete `pre-push` hook if it exists (It might be deleted already or be empty in which case there is no need to delete but on the other hand there is no harm in deletion :p)
4) Now type `gtm init --local` to initialize tracking in local mode
5) Type `git push origin --delete refs/notes/gtm-data` <- deletes data from remote
6) Should be good to go, if there are no conflicts on git fetch nor git push, you can delete the previously made backup

**Comment by bestlinuxgamers** [comment]
I really appreciate the help! Everything has worked for me.
Maybe it would be a good idea to make pushing the remote opt in and not opt out. The option could also be made non optimal. This way, each initialize must be decided and there is no confusion.
Additionally I wanted to ask if the Intellij plugin has the setting to initialize gtm locally.

**Comment by kilpkonn** [comment]
I'm thinking of maybe adding per pc settings file where you can store the default option.
For Jetbrains, there is currently no option, I guess we could add 3 buttons to popup: Add `local tracking`, `add tracking`, `no tracking` etc. 

I might look into adding this option in a week or so, If you wish you can create a merge request as well, which would be highly appreciated!

Anyways, thanks for the feedback!

**Comment by bestlinuxgamers** [comment]
Thanks again for the help!
